runtime: nodejs14
service: default
instance_class: F1

automatic_scaling:
    max_concurrent_requests: 50
    max_instances: 15
    min_idle_instances: 1

handlers:
    - url: /.*
      script: auto
      secure: always

env_variables:
    NODE_ENV: production
