name: Deploy to gae
on: [push]
jobs:
    build:
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Deploy to App Engine
              id: deploy
              uses: google-github-actions/deploy-appengine@v0.2.0
              with:
                project_id: ${{ secrets.GCP_PROJECT }}
                credentials: ${{ secrets.GCP_SA_KEY }}
                version: v1
            - name: Show Output
              run: echo ${{ steps.deploy.outputs.url }}