name: Main Workflow
on: [push]
jobs:
    build:
        name: Run k6 test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run k6 local test
              uses: k6io/action@v0.1
              with:
                  filename: ./k6-load-scripts/test-load.js
                  flags: --vus 50 --duration 10s
